/* Generated by MyraPad at 04/06/2020 17:23:06 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace Mayday.UI
{
	partial class MainMenuUserInterface: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Mayday";
			label1.TextColor = Color.Orange;
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			MenuSinglePlayer = new ImageTextButton();
			MenuSinglePlayer.Text = "Single Player";
			MenuSinglePlayer.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MenuSinglePlayer.Margin = new Thickness(0, 0, 0, 10);
			MenuSinglePlayer.Padding = new Thickness(10);
			MenuSinglePlayer.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MenuSinglePlayer.Id = "MenuSinglePlayer";

			MenuMultiPlayer = new ImageTextButton();
			MenuMultiPlayer.Text = "Multiplayer";
			MenuMultiPlayer.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MenuMultiPlayer.Margin = new Thickness(0, 0, 0, 10);
			MenuMultiPlayer.Padding = new Thickness(10);
			MenuMultiPlayer.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MenuMultiPlayer.Id = "MenuMultiPlayer";

			MenuSettings = new ImageTextButton();
			MenuSettings.Text = "Settings";
			MenuSettings.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MenuSettings.Margin = new Thickness(0, 0, 0, 10);
			MenuSettings.Padding = new Thickness(10);
			MenuSettings.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MenuSettings.Id = "MenuSettings";

			MenuQuit = new ImageTextButton();
			MenuQuit.Text = "Quit";
			MenuQuit.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MenuQuit.Padding = new Thickness(10);
			MenuQuit.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MenuQuit.Id = "MenuQuit";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			verticalStackPanel1.Padding = new Thickness(10);
			verticalStackPanel1.Background = new SolidBrush("#3D3D3D23");
			verticalStackPanel1.Border = new SolidBrush("#E0DEFFFF");
			verticalStackPanel1.Widgets.Add(MenuSinglePlayer);
			verticalStackPanel1.Widgets.Add(MenuMultiPlayer);
			verticalStackPanel1.Widgets.Add(MenuSettings);
			verticalStackPanel1.Widgets.Add(MenuQuit);

			
			Padding = new Thickness(10);
			Widgets.Add(label1);
			Widgets.Add(verticalStackPanel1);
		}

		
		public ImageTextButton MenuSinglePlayer;
		public ImageTextButton MenuMultiPlayer;
		public ImageTextButton MenuSettings;
		public ImageTextButton MenuQuit;
	}
}