/* Generated by MyraPad at 05/06/2020 18:14:44 */

using Myra.Graphics2D.UI;

namespace Mayday.UI.Views
{
	public partial class GameScreenUserInterface
	{
		public GameScreenUserInterface()
		{
			BuildUI();
		}

	}
}