/* Generated by MyraPad at 04/06/2020 21:41:30 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace Mayday.UI.Views
{
	partial class MainMenuUserInterface: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Mayday";
			label1.Margin = new Thickness(0, 0, 0, 10);
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			MenuSinglePlayer = new ImageTextButton();
			MenuSinglePlayer.Text = "Single Player";
			MenuSinglePlayer.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MenuSinglePlayer.Margin = new Thickness(0, 0, 0, 10);
			MenuSinglePlayer.Padding = new Thickness(10);
			MenuSinglePlayer.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MenuSinglePlayer.Id = "MenuSinglePlayer";

			MenuMultiPlayer = new ImageTextButton();
			MenuMultiPlayer.Text = "Multiplayer";
			MenuMultiPlayer.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MenuMultiPlayer.Margin = new Thickness(0, 0, 0, 10);
			MenuMultiPlayer.Padding = new Thickness(10);
			MenuMultiPlayer.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MenuMultiPlayer.Id = "MenuMultiPlayer";

			MenuSettings = new ImageTextButton();
			MenuSettings.Text = "Settings";
			MenuSettings.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MenuSettings.Margin = new Thickness(0, 0, 0, 10);
			MenuSettings.Padding = new Thickness(10);
			MenuSettings.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MenuSettings.Id = "MenuSettings";

			MenuQuit = new ImageTextButton();
			MenuQuit.Text = "Quit";
			MenuQuit.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MenuQuit.Padding = new Thickness(10);
			MenuQuit.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MenuQuit.Id = "MenuQuit";

			MainPanel = new VerticalStackPanel();
			MainPanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			MainPanel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			MainPanel.Width = 200;
			MainPanel.Padding = new Thickness(10);
			MainPanel.Visible = false;
			MainPanel.Background = new SolidBrush("#3D3D3D23");
			MainPanel.Border = new SolidBrush("#E0DEFFFF");
			MainPanel.Id = "MainPanel";
			MainPanel.Widgets.Add(label1);
			MainPanel.Widgets.Add(MenuSinglePlayer);
			MainPanel.Widgets.Add(MenuMultiPlayer);
			MainPanel.Widgets.Add(MenuSettings);
			MainPanel.Widgets.Add(MenuQuit);

			var label2 = new Label();
			label2.Text = "Single Player";
			label2.Margin = new Thickness(0, 0, 0, 10);
			label2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			StartGameNewGame = new ImageTextButton();
			StartGameNewGame.Text = "New Game";
			StartGameNewGame.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			StartGameNewGame.Margin = new Thickness(0, 0, 0, 10);
			StartGameNewGame.Padding = new Thickness(10);
			StartGameNewGame.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			StartGameNewGame.Id = "StartGameNewGame";

			StartGameLoadGame = new ImageTextButton();
			StartGameLoadGame.Text = "Load Game";
			StartGameLoadGame.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			StartGameLoadGame.Margin = new Thickness(0, 0, 0, 10);
			StartGameLoadGame.Padding = new Thickness(10);
			StartGameLoadGame.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			StartGameLoadGame.Id = "StartGameLoadGame";

			StartGameBack = new ImageTextButton();
			StartGameBack.Text = "Back";
			StartGameBack.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			StartGameBack.Padding = new Thickness(10);
			StartGameBack.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			StartGameBack.Id = "StartGameBack";

			StartGamePanel = new VerticalStackPanel();
			StartGamePanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			StartGamePanel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			StartGamePanel.Width = 200;
			StartGamePanel.Padding = new Thickness(10);
			StartGamePanel.Visible = false;
			StartGamePanel.Background = new SolidBrush("#3D3D3D23");
			StartGamePanel.Border = new SolidBrush("#E0DEFFFF");
			StartGamePanel.Id = "StartGamePanel";
			StartGamePanel.Widgets.Add(label2);
			StartGamePanel.Widgets.Add(StartGameNewGame);
			StartGamePanel.Widgets.Add(StartGameLoadGame);
			StartGamePanel.Widgets.Add(StartGameBack);

			var label3 = new Label();
			label3.Text = "Multiplayer";
			label3.Margin = new Thickness(0, 0, 0, 10);
			label3.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			MultiPlayerCreateGame = new ImageTextButton();
			MultiPlayerCreateGame.Text = "Create Game";
			MultiPlayerCreateGame.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MultiPlayerCreateGame.Margin = new Thickness(0, 0, 0, 10);
			MultiPlayerCreateGame.Padding = new Thickness(10);
			MultiPlayerCreateGame.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MultiPlayerCreateGame.Id = "MultiPlayerCreateGame";

			MultiPlayerJoinByIp = new ImageTextButton();
			MultiPlayerJoinByIp.Text = "Join by IP";
			MultiPlayerJoinByIp.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MultiPlayerJoinByIp.Margin = new Thickness(0, 0, 0, 10);
			MultiPlayerJoinByIp.Padding = new Thickness(10);
			MultiPlayerJoinByIp.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MultiPlayerJoinByIp.Id = "MultiPlayerJoinByIp";

			MultiPlayerJoinBySteam = new ImageTextButton();
			MultiPlayerJoinBySteam.Text = "Join by Steam";
			MultiPlayerJoinBySteam.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MultiPlayerJoinBySteam.Margin = new Thickness(0, 0, 0, 10);
			MultiPlayerJoinBySteam.Padding = new Thickness(10);
			MultiPlayerJoinBySteam.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MultiPlayerJoinBySteam.Id = "MultiPlayerJoinBySteam";

			MultiPlayerBack = new ImageTextButton();
			MultiPlayerBack.Text = "Back";
			MultiPlayerBack.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MultiPlayerBack.Padding = new Thickness(10);
			MultiPlayerBack.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MultiPlayerBack.Id = "MultiPlayerBack";

			MultiPlayerPanel = new VerticalStackPanel();
			MultiPlayerPanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			MultiPlayerPanel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			MultiPlayerPanel.Width = 200;
			MultiPlayerPanel.Padding = new Thickness(10);
			MultiPlayerPanel.Visible = false;
			MultiPlayerPanel.Background = new SolidBrush("#3D3D3D23");
			MultiPlayerPanel.Border = new SolidBrush("#E0DEFFFF");
			MultiPlayerPanel.Id = "MultiPlayerPanel";
			MultiPlayerPanel.Widgets.Add(label3);
			MultiPlayerPanel.Widgets.Add(MultiPlayerCreateGame);
			MultiPlayerPanel.Widgets.Add(MultiPlayerJoinByIp);
			MultiPlayerPanel.Widgets.Add(MultiPlayerJoinBySteam);
			MultiPlayerPanel.Widgets.Add(MultiPlayerBack);

			var label4 = new Label();
			label4.Text = "Settings";
			label4.Margin = new Thickness(0, 0, 0, 10);
			label4.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			SettingsBack = new ImageTextButton();
			SettingsBack.Text = "Back";
			SettingsBack.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			SettingsBack.Padding = new Thickness(10);
			SettingsBack.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			SettingsBack.Id = "SettingsBack";

			SettingsPanel = new VerticalStackPanel();
			SettingsPanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			SettingsPanel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			SettingsPanel.Width = 200;
			SettingsPanel.Padding = new Thickness(10);
			SettingsPanel.Visible = false;
			SettingsPanel.Background = new SolidBrush("#3D3D3D23");
			SettingsPanel.Border = new SolidBrush("#E0DEFFFF");
			SettingsPanel.Id = "SettingsPanel";
			SettingsPanel.Widgets.Add(label4);
			SettingsPanel.Widgets.Add(SettingsBack);

			var label5 = new Label();
			label5.Text = "Join by IP";
			label5.Margin = new Thickness(0, 0, 0, 10);
			label5.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var label6 = new Label();
			label6.Text = "IP Address:";
			label6.Margin = new Thickness(0, 0, 0, 10);

			IpAddressTextBox = new TextBox();
			IpAddressTextBox.Margin = new Thickness(0, 0, 0, 10);
			IpAddressTextBox.Padding = new Thickness(10);
			IpAddressTextBox.Id = "IpAddressTextBox";

			var label7 = new Label();
			label7.Text = "Port:";
			label7.Margin = new Thickness(0, 0, 0, 10);

			PortTextBox = new TextBox();
			PortTextBox.Text = "25565";
			PortTextBox.Margin = new Thickness(0, 0, 0, 10);
			PortTextBox.Padding = new Thickness(10);
			PortTextBox.Id = "PortTextBox";

			JoinByIpJoin = new ImageTextButton();
			JoinByIpJoin.Text = "Join";
			JoinByIpJoin.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			JoinByIpJoin.Margin = new Thickness(0, 0, 0, 10);
			JoinByIpJoin.Padding = new Thickness(10);
			JoinByIpJoin.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			JoinByIpJoin.Id = "JoinByIpJoin";

			JoinByIpBack = new ImageTextButton();
			JoinByIpBack.Text = "Back";
			JoinByIpBack.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			JoinByIpBack.Padding = new Thickness(10);
			JoinByIpBack.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			JoinByIpBack.Id = "JoinByIpBack";

			JoinByIpPanel = new VerticalStackPanel();
			JoinByIpPanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			JoinByIpPanel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			JoinByIpPanel.Width = 200;
			JoinByIpPanel.Padding = new Thickness(10);
			JoinByIpPanel.Visible = false;
			JoinByIpPanel.Background = new SolidBrush("#3D3D3D23");
			JoinByIpPanel.Border = new SolidBrush("#E0DEFFFF");
			JoinByIpPanel.Id = "JoinByIpPanel";
			JoinByIpPanel.Widgets.Add(label5);
			JoinByIpPanel.Widgets.Add(label6);
			JoinByIpPanel.Widgets.Add(IpAddressTextBox);
			JoinByIpPanel.Widgets.Add(label7);
			JoinByIpPanel.Widgets.Add(PortTextBox);
			JoinByIpPanel.Widgets.Add(JoinByIpJoin);
			JoinByIpPanel.Widgets.Add(JoinByIpBack);

			var label8 = new Label();
			label8.Text = "Yetiface";
			label8.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label8.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

			
			Padding = new Thickness(10);
			Widgets.Add(MainPanel);
			Widgets.Add(StartGamePanel);
			Widgets.Add(MultiPlayerPanel);
			Widgets.Add(SettingsPanel);
			Widgets.Add(JoinByIpPanel);
			Widgets.Add(label8);
		}

		
		public ImageTextButton MenuSinglePlayer;
		public ImageTextButton MenuMultiPlayer;
		public ImageTextButton MenuSettings;
		public ImageTextButton MenuQuit;
		public VerticalStackPanel MainPanel;
		public ImageTextButton StartGameNewGame;
		public ImageTextButton StartGameLoadGame;
		public ImageTextButton StartGameBack;
		public VerticalStackPanel StartGamePanel;
		public ImageTextButton MultiPlayerCreateGame;
		public ImageTextButton MultiPlayerJoinByIp;
		public ImageTextButton MultiPlayerJoinBySteam;
		public ImageTextButton MultiPlayerBack;
		public VerticalStackPanel MultiPlayerPanel;
		public ImageTextButton SettingsBack;
		public VerticalStackPanel SettingsPanel;
		public TextBox IpAddressTextBox;
		public TextBox PortTextBox;
		public ImageTextButton JoinByIpJoin;
		public ImageTextButton JoinByIpBack;
		public VerticalStackPanel JoinByIpPanel;
	}
}