/* Generated by MyraPad at 05/06/2020 02:52:15 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace Mayday.UI.Views
{
	partial class MainMenuUserInterface: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Yetiface";
			label1.Margin = new Thickness(0, 10);
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			label1.GridRow = 1;

			GameLogo = new Image();
			GameLogo.Width = 284;
			GameLogo.Height = 64;
			GameLogo.Margin = new Thickness(0, 0, 0, 50);
			GameLogo.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			GameLogo.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			GameLogo.Id = "GameLogo";

			MenuSinglePlayer = new ImageTextButton();
			MenuSinglePlayer.Text = "Single Player";
			MenuSinglePlayer.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MenuSinglePlayer.Margin = new Thickness(0, 0, 0, 10);
			MenuSinglePlayer.Padding = new Thickness(10);
			MenuSinglePlayer.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MenuSinglePlayer.Background = new SolidBrush("#8d697a");
			MenuSinglePlayer.OverBackground = new SolidBrush("#544e68");
			MenuSinglePlayer.FocusedBackground = new SolidBrush("#203c56");
			MenuSinglePlayer.Id = "MenuSinglePlayer";

			MenuMultiPlayer = new ImageTextButton();
			MenuMultiPlayer.Text = "Multiplayer";
			MenuMultiPlayer.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MenuMultiPlayer.Margin = new Thickness(0, 0, 0, 10);
			MenuMultiPlayer.Padding = new Thickness(10);
			MenuMultiPlayer.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MenuMultiPlayer.Background = new SolidBrush("#8d697a");
			MenuMultiPlayer.OverBackground = new SolidBrush("#544e68");
			MenuMultiPlayer.FocusedBackground = new SolidBrush("#203c56");
			MenuMultiPlayer.Id = "MenuMultiPlayer";

			MenuSettings = new ImageTextButton();
			MenuSettings.Text = "Settings";
			MenuSettings.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MenuSettings.Margin = new Thickness(0, 0, 0, 10);
			MenuSettings.Padding = new Thickness(10);
			MenuSettings.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MenuSettings.Background = new SolidBrush("#8d697a");
			MenuSettings.OverBackground = new SolidBrush("#544e68");
			MenuSettings.FocusedBackground = new SolidBrush("#203c56");
			MenuSettings.Id = "MenuSettings";

			MenuQuit = new ImageTextButton();
			MenuQuit.Text = "Quit";
			MenuQuit.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MenuQuit.Padding = new Thickness(10);
			MenuQuit.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MenuQuit.Background = new SolidBrush("#8d697a");
			MenuQuit.OverBackground = new SolidBrush("#544e68");
			MenuQuit.FocusedBackground = new SolidBrush("#203c56");
			MenuQuit.Id = "MenuQuit";

			MainPanel = new VerticalStackPanel();
			MainPanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MainPanel.Width = 200;
			MainPanel.Padding = new Thickness(10);
			MainPanel.Id = "MainPanel";
			MainPanel.Widgets.Add(MenuSinglePlayer);
			MainPanel.Widgets.Add(MenuMultiPlayer);
			MainPanel.Widgets.Add(MenuSettings);
			MainPanel.Widgets.Add(MenuQuit);

			StartGameNewGame = new ImageTextButton();
			StartGameNewGame.Text = "New Game";
			StartGameNewGame.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			StartGameNewGame.Margin = new Thickness(0, 0, 0, 10);
			StartGameNewGame.Padding = new Thickness(10);
			StartGameNewGame.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			StartGameNewGame.Background = new SolidBrush("#8d697a");
			StartGameNewGame.OverBackground = new SolidBrush("#544e68");
			StartGameNewGame.FocusedBackground = new SolidBrush("#203c56");
			StartGameNewGame.Id = "StartGameNewGame";

			StartGameLoadGame = new ImageTextButton();
			StartGameLoadGame.Text = "Load Game";
			StartGameLoadGame.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			StartGameLoadGame.Margin = new Thickness(0, 0, 0, 10);
			StartGameLoadGame.Padding = new Thickness(10);
			StartGameLoadGame.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			StartGameLoadGame.Background = new SolidBrush("#8d697a");
			StartGameLoadGame.OverBackground = new SolidBrush("#544e68");
			StartGameLoadGame.FocusedBackground = new SolidBrush("#203c56");
			StartGameLoadGame.Id = "StartGameLoadGame";

			StartGameBack = new ImageTextButton();
			StartGameBack.Text = "Back";
			StartGameBack.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			StartGameBack.Padding = new Thickness(10);
			StartGameBack.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			StartGameBack.Background = new SolidBrush("#8d697a");
			StartGameBack.OverBackground = new SolidBrush("#544e68");
			StartGameBack.FocusedBackground = new SolidBrush("#203c56");
			StartGameBack.Id = "StartGameBack";

			StartGamePanel = new VerticalStackPanel();
			StartGamePanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			StartGamePanel.Width = 200;
			StartGamePanel.Padding = new Thickness(10);
			StartGamePanel.Visible = false;
			StartGamePanel.Id = "StartGamePanel";
			StartGamePanel.Widgets.Add(StartGameNewGame);
			StartGamePanel.Widgets.Add(StartGameLoadGame);
			StartGamePanel.Widgets.Add(StartGameBack);

			MultiPlayerCreateGame = new ImageTextButton();
			MultiPlayerCreateGame.Text = "Create Game";
			MultiPlayerCreateGame.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MultiPlayerCreateGame.Margin = new Thickness(0, 0, 0, 10);
			MultiPlayerCreateGame.Padding = new Thickness(10);
			MultiPlayerCreateGame.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MultiPlayerCreateGame.Background = new SolidBrush("#8d697a");
			MultiPlayerCreateGame.OverBackground = new SolidBrush("#544e68");
			MultiPlayerCreateGame.FocusedBackground = new SolidBrush("#203c56");
			MultiPlayerCreateGame.Id = "MultiPlayerCreateGame";

			MultiPlayerJoinByIp = new ImageTextButton();
			MultiPlayerJoinByIp.Text = "Join by IP";
			MultiPlayerJoinByIp.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MultiPlayerJoinByIp.Margin = new Thickness(0, 0, 0, 10);
			MultiPlayerJoinByIp.Padding = new Thickness(10);
			MultiPlayerJoinByIp.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MultiPlayerJoinByIp.Background = new SolidBrush("#8d697a");
			MultiPlayerJoinByIp.OverBackground = new SolidBrush("#544e68");
			MultiPlayerJoinByIp.FocusedBackground = new SolidBrush("#203c56");
			MultiPlayerJoinByIp.Id = "MultiPlayerJoinByIp";

			MultiPlayerJoinBySteam = new ImageTextButton();
			MultiPlayerJoinBySteam.Text = "Join by Steam";
			MultiPlayerJoinBySteam.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MultiPlayerJoinBySteam.Margin = new Thickness(0, 0, 0, 10);
			MultiPlayerJoinBySteam.Padding = new Thickness(10);
			MultiPlayerJoinBySteam.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MultiPlayerJoinBySteam.Background = new SolidBrush("#8d697a");
			MultiPlayerJoinBySteam.OverBackground = new SolidBrush("#544e68");
			MultiPlayerJoinBySteam.FocusedBackground = new SolidBrush("#203c56");
			MultiPlayerJoinBySteam.Id = "MultiPlayerJoinBySteam";

			MultiPlayerBack = new ImageTextButton();
			MultiPlayerBack.Text = "Back";
			MultiPlayerBack.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MultiPlayerBack.Padding = new Thickness(10);
			MultiPlayerBack.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			MultiPlayerBack.Background = new SolidBrush("#8d697a");
			MultiPlayerBack.OverBackground = new SolidBrush("#544e68");
			MultiPlayerBack.FocusedBackground = new SolidBrush("#203c56");
			MultiPlayerBack.Id = "MultiPlayerBack";

			MultiPlayerPanel = new VerticalStackPanel();
			MultiPlayerPanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MultiPlayerPanel.Width = 200;
			MultiPlayerPanel.Padding = new Thickness(10);
			MultiPlayerPanel.Visible = false;
			MultiPlayerPanel.Id = "MultiPlayerPanel";
			MultiPlayerPanel.Widgets.Add(MultiPlayerCreateGame);
			MultiPlayerPanel.Widgets.Add(MultiPlayerJoinByIp);
			MultiPlayerPanel.Widgets.Add(MultiPlayerJoinBySteam);
			MultiPlayerPanel.Widgets.Add(MultiPlayerBack);

			SettingsBack = new ImageTextButton();
			SettingsBack.Text = "Back";
			SettingsBack.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			SettingsBack.Padding = new Thickness(10);
			SettingsBack.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			SettingsBack.Background = new SolidBrush("#8d697a");
			SettingsBack.OverBackground = new SolidBrush("#544e68");
			SettingsBack.FocusedBackground = new SolidBrush("#203c56");
			SettingsBack.Id = "SettingsBack";

			SettingsPanel = new VerticalStackPanel();
			SettingsPanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			SettingsPanel.Width = 200;
			SettingsPanel.Padding = new Thickness(10);
			SettingsPanel.Visible = false;
			SettingsPanel.Id = "SettingsPanel";
			SettingsPanel.Widgets.Add(SettingsBack);

			IpAddressTextBox = new TextBox();
			IpAddressTextBox.HintText = "IP Address";
			IpAddressTextBox.Margin = new Thickness(0, 0, 0, 10);
			IpAddressTextBox.Padding = new Thickness(10);
			IpAddressTextBox.Background = new SolidBrush("#8d697a");
			IpAddressTextBox.OverBackground = new SolidBrush("#544e68");
			IpAddressTextBox.FocusedBackground = new SolidBrush("#203c56");
			IpAddressTextBox.Id = "IpAddressTextBox";

			PortTextBox = new TextBox();
			PortTextBox.HintText = "Port";
			PortTextBox.Text = "25565";
			PortTextBox.Margin = new Thickness(0, 0, 0, 10);
			PortTextBox.Padding = new Thickness(10);
			PortTextBox.Background = new SolidBrush("#8d697a");
			PortTextBox.OverBackground = new SolidBrush("#544e68");
			PortTextBox.FocusedBackground = new SolidBrush("#203c56");
			PortTextBox.Id = "PortTextBox";

			JoinByIpJoin = new ImageTextButton();
			JoinByIpJoin.Text = "Join";
			JoinByIpJoin.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			JoinByIpJoin.Margin = new Thickness(0, 0, 0, 10);
			JoinByIpJoin.Padding = new Thickness(10);
			JoinByIpJoin.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			JoinByIpJoin.Background = new SolidBrush("#8d697a");
			JoinByIpJoin.OverBackground = new SolidBrush("#544e68");
			JoinByIpJoin.FocusedBackground = new SolidBrush("#203c56");
			JoinByIpJoin.Id = "JoinByIpJoin";

			JoinByIpBack = new ImageTextButton();
			JoinByIpBack.Text = "Back";
			JoinByIpBack.ContentHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			JoinByIpBack.Padding = new Thickness(10);
			JoinByIpBack.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			JoinByIpBack.Background = new SolidBrush("#8d697a");
			JoinByIpBack.OverBackground = new SolidBrush("#544e68");
			JoinByIpBack.FocusedBackground = new SolidBrush("#203c56");
			JoinByIpBack.Id = "JoinByIpBack";

			JoinByIpPanel = new VerticalStackPanel();
			JoinByIpPanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			JoinByIpPanel.Width = 200;
			JoinByIpPanel.Padding = new Thickness(10);
			JoinByIpPanel.Visible = false;
			JoinByIpPanel.Id = "JoinByIpPanel";
			JoinByIpPanel.Widgets.Add(IpAddressTextBox);
			JoinByIpPanel.Widgets.Add(PortTextBox);
			JoinByIpPanel.Widgets.Add(JoinByIpJoin);
			JoinByIpPanel.Widgets.Add(JoinByIpBack);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.GridRow = 1;
			verticalStackPanel1.Widgets.Add(MainPanel);
			verticalStackPanel1.Widgets.Add(StartGamePanel);
			verticalStackPanel1.Widgets.Add(MultiPlayerPanel);
			verticalStackPanel1.Widgets.Add(SettingsPanel);
			verticalStackPanel1.Widgets.Add(JoinByIpPanel);

			var grid1 = new Grid();
			grid1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			grid1.Widgets.Add(GameLogo);
			grid1.Widgets.Add(verticalStackPanel1);

			
			Padding = new Thickness(10);
			Widgets.Add(label1);
			Widgets.Add(grid1);
		}

		
		public Image GameLogo;
		public ImageTextButton MenuSinglePlayer;
		public ImageTextButton MenuMultiPlayer;
		public ImageTextButton MenuSettings;
		public ImageTextButton MenuQuit;
		public VerticalStackPanel MainPanel;
		public ImageTextButton StartGameNewGame;
		public ImageTextButton StartGameLoadGame;
		public ImageTextButton StartGameBack;
		public VerticalStackPanel StartGamePanel;
		public ImageTextButton MultiPlayerCreateGame;
		public ImageTextButton MultiPlayerJoinByIp;
		public ImageTextButton MultiPlayerJoinBySteam;
		public ImageTextButton MultiPlayerBack;
		public VerticalStackPanel MultiPlayerPanel;
		public ImageTextButton SettingsBack;
		public VerticalStackPanel SettingsPanel;
		public TextBox IpAddressTextBox;
		public TextBox PortTextBox;
		public ImageTextButton JoinByIpJoin;
		public ImageTextButton JoinByIpBack;
		public VerticalStackPanel JoinByIpPanel;
	}
}